<div id="modalSobre" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Sobre</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
            </div>
            <div class="modal-body" style="text-align: center">
                <p>
                    <h6>Generated by:</h6>
                    <h4><img src="img/logo.png" /> Kirn</h4>
                    <h6>Framework Container</h6>
                    <h8>Created by &COPY; 2014 <a href="http://www.luizleao.com" target="_blank">Luiz Leão</a>. Software License <a href="http://www.gnu.org/copyleft/lesser.txt" target="_blank">GPL</a></h8>
                </p>
            </div>
            <div class="modal-footer">
                <button id="btnFechar" class="btn btn-primary" autofocus="autofocus" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>