<div id="modalSobre" class="modal hide fade">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">×</button>
		<h3>Sobre</h3>
	</div>
	<div class="modal-body">
		<p>
		
		
		<h6>Generated by:</h6>
		<h4>
			<img src="img/logo.png" /> Kirn
		</h4>
		<h6>Framework Container</h6>
		<h8>Created by &#169; 2014 <a href="http://www.luizleao.com"
			target="_blank">Luiz Leão</a>. Software License <a
			href="http://www.gnu.org/copyleft/lesser.txt" target="_blank">GPL</a></h8>
		</p>
	</div>
	<div class="modal-footer">
		<button id="btnFechar" type="button" class="btn btn-primary"
			data-dismiss="modal" autofocus="autofocus">Fechar</button>
	</div>
</div>